
baseURL = 'https://freiheit.wtf/'
copyright = 'Â© 2023-2025 Freiheit.wtf'

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

languageCode = 'en-us'

pagination.pagerSize = 5

sectionPagesMenu = 'main'

theme = 're-terminal'

title = 'freiheit.wtf'

timeZone = 'America/Los_Angeles'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'RSS Feed'
    url = '/posts/index.xml'
    weight = 300

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:slug/'

[taxonomies]
  tag = 'tags'

[markup.highlight]
  noClasses = false

[params]
  subtitle = 'Just some guy, you know?'

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  favicon = "favicon.ico"

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  readingTime = true

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default
  Toc = false

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  [params.author]
    name = 'freiheit'
    email = 'busy.vest9723@freiheit.wtf'
  [params.contact]
    email = 'busy.vest9723@freiheit.wtf'

  [params.logo]
    logoText = "freiheit"
    logoHomeLink = "/"
