name: Build and Deploy to Fastmail

on:
  push:
    branches:
      - main
  schedule:
    - cron: "23 6 * * *"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.152.2"
          extended: true

      - name: Build
        run: hugo --logLevel debug --destination public

      - name: List directory contents
        run: ls -la public

      - name: Persist build
        uses: actions/upload-artifact@v6
        with:
          name: website
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build
        uses: actions/download-artifact@v7
        with:
          path: website
          name: website

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Create rclone.conf
        run: |
          echo "[webdav]
          type = webdav
          url = ${{ secrets.WEBDAV_URL }}
          vendor = fastmail
          user = ${{ secrets.WEBDAV_USERNAME }}
          pass = ${{ secrets.WEBDAV_PASSWORD }}" > rclone.conf

      - name: Backup remote directory
        run: |
          mkdir backup
          rclone --config rclone.conf sync webdav:${{ secrets.WEBDAV_PATH }} backup

      - name: Persist backup
        uses: actions/upload-artifact@v6
        with:
          name: backup
          path: backup

      #- name: Clear remote directory but do not delete the root folder
      #  run: |
      #    rclone --config rclone.conf delete webdav:${{ secrets.WEBDAV_PATH }}
      #    rclone --config rclone.conf rmdirs --leave-root webdav:${{ secrets.WEBDAV_PATH }}

      - name: Deploy to WebDAV with rclone
        run: |
          rclone --config rclone.conf sync ./website webdav:${{ secrets.WEBDAV_PATH }} || exit 1

      - name: Failover
        run: |
          if [ $? -eq 1 ]; then
            echo "rclone failed. Restoring original website files."
            rclone --config rclone.conf copy backup webdav:${{ secrets.WEBDAV_PATH }}
          fi

      - name: Cleanup
        run: rm rclone.conf
